<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
  <Compile Remove="Week1.Rbac.Api\**" />
  <Content Remove="Week1.Rbac.Api\**" />
  <EmbeddedResource Remove="Week1.Rbac.Api\**" />
  <None Remove="Week1.Rbac.Api\**" />
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>
